/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Inline_response_200 (
  json: Option[Inline_response_200_json],
  links: Option[Inline_response_200_links],
  data: Seq[Inline_response_200_data]
) extends ApiModel


