/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Invoice (
  /* Unique identifier which holds the invoice id */
  id: String,
  /* Date on which invoice is generated */
  date: String,
  /* Gross amount for the invoice */
  amount: Double,
  /* Represents the status of invoice */
  status: InvoiceEnums.Status,
  /* Represents the type of invoice */
  `type`: InvoiceEnums.&#x60;Type&#x60;,
  /* Contract account number for the generated invoice */
  `contract-account-number`: String
) extends ApiModel

object InvoiceEnums {

  type Status = Status.Value
  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object Status extends Enumeration {
    val Debit = Value("debit")
    val Credit = Value("credit")
  }

  object &#x60;Type&#x60; extends Enumeration {
    val Invoice = Value("Invoice")
    val `Credit note` = Value("Credit note")
  }

}

